### ISSUE TITLE
[FE] HTML

### ISSUE THREAD

**Issue by leechanmul** [codesquad-member-2020/signup-7#3]
# HTML
- [x] Sign Up View HTML
- [x] Index(Sign In) View HTML

## 요구 사항
- [x] 아이디, 비밀번호, 비밀번호 재확인, 이름, 생년월일, 성별, 이메일, 휴대전화, 관심사 총 9개의 입력 항목
- [x] 년 placeholder "년(4자)"
- [x] 월 1에서 12까지 선택 가능 기본값 "월"
- [x] 일 placeholder "일"
- [x] 성별 남자/여자 기본값 "성별"
- [x] 휴대전화 placeholder "- 없이 입력해주세요. 예) 01012341234"

**Comment by haveagood** [comment]
오오!! HTML!! 이게 필요했어요!!ㅋㅋㅋ

**Comment by leechanmul** [comment]
# 고민했던 것
- 웹 표준에서 `input` 앞에 `label` 태그를 사용하는데 생년월일은 두 개의 `input` 태그와 하나의 `select` 태그로 구성되어 `label`을 어떻게 사용해야 하는지 고민함
- `aria-label`와 `aria-labelledby`를 배우고 사용하여 해결함

## 참고한 사이트
- https://developers.google.com/web/fundamentals/accessibility/semantics-aria/aria-labels-and-relationships?hl=ko
- https://developer.mozilla.org/ko/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute
